# Create environment with `conda env create -f environment.yml`
# Activate environment with `conda activate pmr`
# Update environment with `conda env update --file environment.yml`
# Remove environment with `conda remove --name pmr --all`

name: pmr
channels:
    - pytorch
    - conda-forge
    - anaconda
dependencies:
    - python=3.8
    - pytorch=1.11.0
    - torchvision=0.12.0
    - numpy=1.21.4
    - matplotlib
    - notebook
    - ipywidgets
    - tqdm